// Auto-generated by scripts/fetch_prints.py — do not edit photo URLs by hand.
// To add or edit titles/descriptions, update this file then re-run the script
// to preserve your edits while refreshing photo URLs.
//
// Run:  python scripts/fetch_prints.py
// Last updated: (not yet run)

const PRINTS = [
  // Photos will appear here after you run: python scripts/fetch_prints.py
];
