#!/usr/bin/env python3
"""
fetch_prints.py — Refresh 3D prints gallery from a Google Photos shared album.

Usage:
    python scripts/fetch_prints.py

This script fetches the public Google Photos shared album, extracts all photo
CDN URLs (lh3.googleusercontent.com), and writes them to prints/data.js which
powers the carousel on /prints.

Any titles/descriptions you've added to data.js are preserved across runs —
the script matches photos by their ID and keeps your metadata.

Requirements:
    pip install requests
"""

import json
import re
import sys
from datetime import datetime
from pathlib import Path

try:
    import requests
except ImportError:
    print("✗ 'requests' not found. Install it with:  pip install requests", file=sys.stderr)
    sys.exit(1)

# ── Config ────────────────────────────────────────────────────────────────────

ALBUM_URL = (
    "https://photos.google.com/share/"
    "AF1QipPT4gMqpVX-B5M9JpEOkdBx7eCDO09TB2LH_wNRlhtfYJ2k4un0W7cbXfsqR66bqg"
    "?key=MnkzTzc0NTlnSF9CdmFHTzVGWjBYZUNIRXZCUEpB"
)

REPO_ROOT   = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "prints" / "data.js"

# Google Photos CDN size parameters
DISPLAY = "w1920-h1080"   # shown in carousel
THUMB   = "w600-h400"     # preload / og:image

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
}

# ── Fetch ─────────────────────────────────────────────────────────────────────

def fetch_album(url: str) -> str:
    print(f"Fetching: {url}")
    try:
        r = requests.get(url, headers=HEADERS, timeout=30)
        r.raise_for_status()
        return r.text
    except requests.RequestException as e:
        print(f"✗ Could not fetch album: {e}", file=sys.stderr)
        sys.exit(1)

# ── Parse ─────────────────────────────────────────────────────────────────────

def extract_photo_ids(html: str) -> list[str]:
    """
    Google Photos shared album pages embed photo data in the page HTML.
    Photo CDN base URLs follow the pattern:
        https://lh3.googleusercontent.com/{photoId}
    where photoId is a long alphanumeric string (≥ 20 chars).

    We extract all unique IDs while preserving their order of appearance,
    which matches the album's display order.
    """
    pattern = r"https://lh3\.googleusercontent\.com/([A-Za-z0-9_\-]{20,})"
    all_ids = re.findall(pattern, html)

    seen: set[str] = set()
    unique: list[str] = []
    for photo_id in all_ids:
        if photo_id not in seen:
            seen.add(photo_id)
            unique.append(photo_id)

    return unique

# ── Preserve existing metadata ────────────────────────────────────────────────

def load_existing(path: Path) -> dict[str, dict]:
    """
    Returns a dict keyed by photo ID → existing entry (with title/description/date).
    This lets us keep hand-written metadata across refreshes.
    """
    if not path.exists():
        return {}
    try:
        text = path.read_text(encoding="utf-8")
        m = re.search(r"const PRINTS\s*=\s*(\[.*?\]);", text, re.DOTALL)
        if not m:
            return {}
        entries = json.loads(m.group(1))
        out = {}
        for entry in entries:
            raw_url = entry.get("url", "")
            m2 = re.search(r"googleusercontent\.com/([A-Za-z0-9_\-]{20,})", raw_url)
            if m2:
                out[m2.group(1)] = entry
        return out
    except Exception as e:
        print(f"Warning: could not parse existing data.js ({e}). Starting fresh.", file=sys.stderr)
        return {}

# ── Build entries ─────────────────────────────────────────────────────────────

def build_prints(photo_ids: list[str], existing: dict[str, dict]) -> list[dict]:
    prints = []
    for i, pid in enumerate(photo_ids):
        base = f"https://lh3.googleusercontent.com/{pid}"
        prev = existing.get(pid, {})
        prints.append({
            "url":         f"{base}={DISPLAY}",
            "thumb":       f"{base}={THUMB}",
            "title":       prev.get("title", f"Print #{i + 1}"),
            "description": prev.get("description", ""),
            "date":        prev.get("date", ""),
        })
    return prints

# ── Write ─────────────────────────────────────────────────────────────────────

TEMPLATE = """\
// Auto-generated by scripts/fetch_prints.py — do not edit photo URLs by hand.
// To add or edit titles/descriptions: update the "title", "description", "date"
// fields below, then re-run the script to preserve your edits while refreshing URLs.
//
// Run:  python scripts/fetch_prints.py
// Album: {album_url}
// Last updated: {date}

const PRINTS = {data};
"""

def write_output(prints: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    content = TEMPLATE.format(
        album_url=ALBUM_URL,
        date=datetime.now().strftime("%Y-%m-%d"),
        data=json.dumps(prints, indent=2, ensure_ascii=False),
    )
    path.write_text(content, encoding="utf-8")
    print(f"✓ Wrote {len(prints)} photos → {path.relative_to(REPO_ROOT)}")

# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    html      = fetch_album(ALBUM_URL)
    ids       = extract_photo_ids(html)

    if not ids:
        print(
            "✗ No photos found.\n"
            "  The album may be empty, private, or Google may have changed the page format.\n"
            "  Try opening the album URL in a browser to check.",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"Found {len(ids)} photo(s).")

    existing = load_existing(OUTPUT_PATH)
    preserved = sum(1 for pid in ids if pid in existing)
    if preserved:
        print(f"Preserving metadata for {preserved} existing photo(s).")

    prints = build_prints(ids, existing)
    write_output(prints, OUTPUT_PATH)

    new_count = len(ids) - preserved
    if new_count:
        print(
            f"\n{new_count} new photo(s) added with placeholder titles.\n"
            f"  Open {OUTPUT_PATH.relative_to(REPO_ROOT)} to add titles/descriptions,\n"
            f"  then re-run this script to lock them in."
        )

    print("\nNext:  git add prints/data.js && git push")

if __name__ == "__main__":
    main()
